:numbered:
:toc: left
:toclevels: 3

= NetRelay^(R)^ Controller


This project is an extension of the project NetRelay and contains several implementations of
`IController`, which are ready to be used, configurable and cover lot of use
cases.

To understand and to use those implementations you should be familar with the use of NetRelay.

For basic information about NetRelay go to the https://github.com/BraintagsGmbH/NetRelay[ NetRelay documentation ]

If you are searching for a very quick entry into NetRelay with a prepared, ready to use project based on NetRelay,
you should go to link:https://github.com/BraintagsGmbH/NetRelay-Demoproject[ Quickstart with NetRelay-Demoproject]

== Using NetRelay-Controller inside your build environments
To use this project, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>de.braintags</groupId>
  <artifactId>NetRelayController</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'de.braintags:NetRelayController:1.0.0-SNAPSHOT'
}
----


== Controllers

Description of the function of existing controllers.

More detailed information about the configuration parameters,
return values etc. can be found inside the javadoc of the corresponding implementation.

=== `RedirectController`
The RedirectController redirects fitting routes to a configurable destination

=== `CurrentMemberController`
If a user is logged in, the propriate record is fetched from the datastore and stored in the context, so that it can
be used by following controllers, like a template controller, for instance

=== `ThymeleafTemplateController`
This controller is used to process templates based on the template engine Thymeleaf

=== `PersistenceController`
The PersistenceController is the instance, which translates the parameters and data of a request into a datastore
based action.

A request like "http://localhost/article/detail?ID=5&entity=article" will be interpreted by the
controller to fetch the article with the id 5 from the datastore and to store it inside the context, so that is can
be displayed by a template engine.

=== Authentication and registration
This package contains several controllers, which can be used to configure and use the complete process of
authentication, registration etc.

==== `AuthenticationController`
All routes, which are covered by this controller are protected.

The controller takes automatically care about login
and logout of users.


==== `RegisterController`
This controller performs a user registration with an integrated automatic double opt in process

==== `PasswordLostController`
The PasswordLostController is used to manage the process for a user, who doesn't remember his password. The process
integrates automatically double opt in.

=== `MailController`

=== `DataTablesController`